---
# - hosts: node_exporter
#   become: yes
#   become_method: sudo
#   roles:
#     - prometheus_node_exporter

# - hosts: consul_exporter
#   become: yes
#   become_method: sudo
#   roles:
#     - prometheus_consul_exporter

- hosts: consul_agent
  become: yes
  become_method: sudo
  roles:
    - consul_agent

- hosts: grafana
  become: yes
  become_method: sudo
  roles:
    - grafana

- hosts: prometheus
  become: yes
  become_method: sudo
  roles:
    - prometheus