- name: Install yum-utils to get yum-config-manager command
  yum:
    name: "yum-utils"
    state: present

- name: Add the repo
  command: "yum-config-manager --add-repo sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"

- name: Installing consul latest package
  yum:
    name: "consul"
    state: present
  when: latest == true

- name: Install the specific version of consul package
  yum:
    name: "consul-{{ version }}.x86_64"
  when: latest != true

- name: Verify If consul is installed
  command: "consul"
  ignore_errors: true

- name: Generate the consul encryption key
  command: "consul keygen"
  register: consul_key

- name: Create consul agent config dirs
  file:
     path: "{{ consul_config_dir }}"
     state: directory
     mode: 0640
     owner: consul
     group: consul

- name: Copy the Consul Agent config file
  template:
    src: consul.hcl.j2
    dest: "{{ consul_config_dir }}/consul.hcl"
    owner: "{{ consul_username }}"
    group: "{{ consul_groupname }}"
    mode: 0644
 # notify: restart_service

- name: Copy the Consul Server config file
  template:
    src: server.hcl.j2
    dest: "{{ consul_config_dir }}/server.hcl"
    owner: "{{ consul_username }}"
    group: "{{ consul_groupname }}"
    mode: 0644
 # notify: restart_service

# - name: Copy the Consul Systemd file
#   template:
#     src: consul.service.j2
#     dest: "/etc/systemd/system/consul.service"
#     owner: "{{ consul_username }}"
#     group: "{{ consul_groupname }}"
#     mode: 0644
#   notify: systemd_reload

- name: Validate the consul agent config file
  command: "consul validate {{ consul_config_dir }}/consul.hcl"
  register: consul_status

# - name: Start the Consul service
#   service:
#     name: "consul"
#     state: started


- name: Start the consule service
  shell: "(consul agent --config-dir={{ consul_config_dir }}/  &)"
  tags:
    - start_consul

- name: Register the node_exporter with consul
  uri:
    url: "http://{{ groups['consul_agent'][0] }}:8500/v1/catalog/register"
    method: POST
    body: "{{ lookup('file','/opt/external.json') }}"
    status_code: 201
    body_format: json